# Generated by Django 2.1.5 on 2019-03-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
