# Generated by Django 2.2.10 on 2020-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190314_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_zone',
            field=models.CharField(default='America/Los_Angeles', max_length=100),
        ),
    ]
