# Generated by Django 2.0.6 on 2018-06-24 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
